# Generated by Django 5.0.3 on 2024-03-22 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('matricula', models.CharField(max_length=10)),
                ('data_de_ingresso', models.DateField(auto_now_add=True)),
                ('endereco', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=15)),
                ('genero', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['data_de_ingresso'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('carga_horaria', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('formacao', models.CharField(max_length=100)),
                ('data_de_contratacao', models.DateField(auto_now_add=True)),
                ('endereco', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=15)),
                ('genero', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['data_de_contratacao'],
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dia_da_semana', models.CharField(max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('alunos', models.ManyToManyField(blank=True, to='Gestoes.aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestoes.curso')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='professor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Gestoes.professor'),
        ),
    ]
